# Generated by Django 4.1.4 on 2022-12-10 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('inscricao', models.DateField(auto_now=True, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('nascimento', models.DateField()),
                ('telefone', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
                ('rg', models.FloatField(max_length=11)),
                ('cpf', models.FloatField()),
                ('bairro', models.CharField(max_length=40)),
                ('rua', models.CharField(max_length=80)),
                ('num_residencia', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DadosAcademia',
            fields=[
                ('dat_medidas', models.DateField(primary_key=True, serialize=False)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('imc', models.FloatField(blank=True, null=True)),
                ('gordura', models.FloatField(blank=True, null=True)),
                ('liquido', models.FloatField(blank=True, null=True)),
                ('pa', models.FloatField(blank=True, null=True)),
                ('pulso', models.FloatField(blank=True, null=True)),
                ('bat_cardiaco', models.FloatField(blank=True, null=True)),
                ('quadriceps', models.FloatField(blank=True, null=True)),
                ('torax', models.FloatField(blank=True, null=True)),
                ('cintura', models.FloatField(blank=True, null=True)),
                ('culote', models.FloatField(blank=True, null=True)),
                ('biceps_D', models.FloatField(blank=True, null=True)),
                ('biceps_E', models.FloatField(blank=True, null=True)),
                ('coxa_D', models.FloatField(blank=True, null=True)),
                ('coxa_E', models.FloatField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.alunos')),
            ],
        ),
    ]
