# Generated by Django 4.1.4 on 2022-12-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosAcademia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_medidas', models.DateField()),
                ('altura', models.FloatField()),
                ('peso', models.FloatField()),
                ('imc', models.FloatField()),
                ('gordura', models.FloatField()),
                ('liquido', models.FloatField()),
                ('pa', models.FloatField()),
                ('pulso', models.FloatField()),
                ('bat_cardiaco', models.FloatField()),
                ('quadriceps', models.FloatField()),
                ('torax', models.FloatField()),
                ('cintura', models.FloatField()),
                ('culote', models.FloatField()),
                ('biceps_D', models.FloatField()),
                ('biceps_E', models.FloatField()),
                ('coxa_D', models.FloatField()),
                ('coxa_E', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='alunos',
            name='name',
        ),
    ]
